In [1]:
import pandas as pd
import numpy as np

In [2]:
car=pd.read_csv('quikr_car.csv')

In [3]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [4]:
car.shape

(892, 6)

In [5]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [6]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [7]:
car['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '3,71,500', '4,35,000', '1,89,700', '3,89,700',
       '3,60,000', '2,95,000', '1,14,990', '10,65,000', '4,70,000',
       '48,000', '1,88,000', '4,65,000', '1,79,999', '21,90,000',
       '23,90,000', '10,75,000', '4,75,000', '10,25,000', '6,15,000',
       '19,00,000', '14,90,000', '15,10,000', '18,50,000', '7,90,000',
       '17,25,000', '12,25,000', '68,000', '9,70,000', '31,00,000',
       '8,99,000', '88,000', '53,000', '5,68,500', '71,000', '5,90,000',
       '7,95,000', '42,000', '1,89,000', '1,62,000', '35,999',
       '29,00,000', '39,999', '50,500', '5,10,000', '8,60,000',
       '5,00,001'], dtype=object)

In [8]:
car['kms_driven'].unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms',
       '24,330 kms', '65,480 kms', '28,028 kms', '2,00,000 kms',
       '99,000 kms', '2,800 kms', '21,000 kms', '11,000 kms',
       '66,000 kms', '3,000 kms', '7,000 kms', '38,500 kms', '37,200 kms',
       '43,200 kms', '24,800 kms', '45,872 kms', '40,000 kms',
       '11,400 kms', '97,200 kms', '52,000 kms', '31,000 kms',
       '1,75,430 kms', '37,000 kms', '65,000 kms', '3,350 kms',
       '75,000 kms', '62,000 kms', '73,000 kms', '2,200 kms',
       '54,870 kms', '34,580 kms', '97,000 kms', '60 kms', '80,200 kms',
       '3,200 kms', '0,000 kms', '5,000 kms', '588 kms', '71,200 kms',
       '1,75,400 kms', '9,300 kms', '56,758 kms', '10,000 kms',
       '56,450 kms', '56,000 kms', '32,700 kms', '9,000 kms', '73 kms',
       '1,60,000 kms', '84,000 kms', '58,559 kms', '57,000 kms',
       '1,70,000 kms', '80,000 kms', '6,821 kms', '23,000 kms',
       '34,000 kms', '1,800 kms', '4,00,000 kms', '48,000 kms',
       '90,000 kms', '12,000 kms', '69,900 kms', '1,66,000 kms',
       '122 kms', '0 kms', '24,000 kms', '36,469 kms', '7,800 kms',
       '24,695 kms', '15,141 kms', '59,910 kms', '1,00,000 kms',
       '4,500 kms', '1,29,000 kms', '300 kms', '1,31,000 kms',
       '1,11,111 kms', '59,466 kms', '25,500 kms', '44,005 kms',
       '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '1,80,000 kms', '53,000 kms', '35,500 kms',
       '22,134 kms', '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms',
       '15,574 kms', '8,000 kms', '55,800 kms', '56,400 kms',
       '72,160 kms', '11,500 kms', '1,33,000 kms', '2,000 kms',
       '88,000 kms', '65,422 kms', '1,17,000 kms', '1,50,000 kms',
       '10,750 kms', '6,800 kms', '5 kms', '9,800 kms', '57,923 kms',
       '30,201 kms', '6,200 kms', '37,518 kms', '24,652 kms', '383 kms',
       '95,000 kms', '3,528 kms', '52,500 kms', '47,900 kms',
       '52,800 kms', '1,95,000 kms', '48,008 kms', '48,247 kms',
       '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms', '49,500 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '38,900 kms',
       '1,37,495 kms', '91,200 kms', '1,46,000 kms', '1,00,800 kms',
       '2,100 kms', '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

In [9]:
car['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

## Quality

    names are pretty inconsistent
    names have company names attached to it
    some names are spam like 'Maruti Ertiga showroom condition with' and 'Well mentained Tata Sumo'
    company: many of the names are not of any company like 'Used', 'URJENT', and so on.
    year has many non-year values
    year is in object. Change to integer
    Price has some value Ask for Price,so we need to remove
    Price has commas in its prices and is in object
    kms_driven has object values with kms at last.
    It has nan values and two rows have 'Petrol' in them
    fuel_type has nan values

## Cleaning

In [10]:
backup=car.copy()

In [11]:
car=car[car['year'].str.isnumeric()]

In [12]:
# Some rows is removed
car.shape

(842, 6)

In [13]:
car['year']=car['year'].astype(int)

In [14]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    int32
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: int32(1), object(5)
memory usage: 42.8+ KB

In [15]:
car=car[car['Price']!='Ask For Price']

In [16]:
car['Price']=car['Price'].str.replace(',','').astype(int)

In [17]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int32
 3   Price       819 non-null    int32
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int32(2), object(4)
memory usage: 38.4+ KB

In [18]:
car['kms_driven']=car['kms_driven'].str.split(' ').str.get(0).str.replace(',','')

In [19]:
car=car[car['kms_driven'].str.isnumeric()]

In [20]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int32
 3   Price       817 non-null    int32
 4   kms_driven  817 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int32(2), object(4)
memory usage: 38.3+ KB

In [21]:
car['kms_driven']=car['kms_driven'].astype(int)

In [22]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int32
 3   Price       817 non-null    int32
 4   kms_driven  817 non-null    int32
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 35.1+ KB

In [23]:
car=car[~car['fuel_type'].isna()]

In [24]:
car['fuel_type'].unique()

array(['Petrol', 'Diesel', 'LPG'], dtype=object)

In [25]:
car['name']=car['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [26]:
car=car.reset_index(drop=True)

In [27]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [28]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int32
 3   Price       816 non-null    int32
 4   kms_driven  816 non-null    int32
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 28.8+ KB

In [29]:
car.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [30]:
x=6000000
car=car[car['Price'] < x].reset_index(drop=True)

In [31]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [32]:
car.to_csv('cleaned car.csv')

## Model

In [33]:
X=car.drop('Price',axis=1)

In [34]:
y=car['Price']

In [35]:
X

                       name   company  year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2         Hyundai Grand i10   Hyundai  2014       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014       36000    Diesel
4                 Ford Figo      Ford  2012       41000    Diesel
..                      ...       ...   ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
811          Tata Indica V2      Tata  2009       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009      132000    Petrol
813            Tata Zest XM      Tata  2018       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 5 columns]

In [36]:
y

0       80000
1      425000
2      325000
3      575000
4      175000
        ...
810    270000
811    110000
812    300000
813    260000
814    390000
Name: Price, Length: 815, dtype: int32

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [38]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [39]:
ohe=OneHotEncoder()
ohe.fit(X[['name','company','fuel_type']])

OneHotEncoder()

In [40]:
ohe.categories_

[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
        'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
        'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
        'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat Diesel',
        'Chevrolet Beat LS', 'Chevrolet Beat LT', 'Chevrolet Beat PS',
        'Chevrolet Cruze LTZ', 'Chevrolet Enjoy', 'Chevrolet Enjoy 1.4',
        'Chevrolet Sail 1.2', 'Chevrolet Sail UVA', 'Chevrolet Spark',
        'Chevrolet Spark 1.0', 'Chevrolet Spark LS', 'Chevrolet Spark LT',
        'Chevrolet Tavera LS', 'Chevrolet Tavera Neo', 'Datsun GO T',
        'Datsun Go Plus', 'Datsun Redi GO', 'Fiat Linea Emotion',
        'Fiat Petra ELX', 'Fiat Punto Emotion', 'Force Motors Force',
        'Force Motors One', 'Ford EcoSport', 'Ford EcoSport Ambiente',
        'Ford EcoSport Titanium', 'Ford EcoSport Trend',
        'Ford Endeavor 4x4', 'Ford Fiesta', 'Ford Fiesta SXi', 'Ford Figo',
        'Ford Figo Diesel', 'Ford Figo Duratorq', 'Ford Figo Petrol',
        'Ford Fusion 1.4', 'Ford Ikon 1.3', 'Ford Ikon 1.6',
        'Hindustan Motors Ambassador', 'Honda Accord', 'Honda Amaze',
        'Honda Amaze 1.2', 'Honda Amaze 1.5', 'Honda Brio', 'Honda Brio V',
        'Honda Brio VX', 'Honda City', 'Honda City 1.5', 'Honda City SV',
        'Honda City VX', 'Honda City ZX', 'Honda Jazz S', 'Honda Jazz VX',
        'Honda Mobilio', 'Honda Mobilio S', 'Honda WR V', 'Hyundai Accent',
        'Hyundai Accent Executive', 'Hyundai Accent GLE',
        'Hyundai Accent GLX', 'Hyundai Creta', 'Hyundai Creta 1.6',
        'Hyundai Elantra 1.8', 'Hyundai Elantra SX', 'Hyundai Elite i20',
        'Hyundai Eon', 'Hyundai Eon D', 'Hyundai Eon Era',
        'Hyundai Eon Magna', 'Hyundai Eon Sportz', 'Hyundai Fluidic Verna',
        'Hyundai Getz', 'Hyundai Getz GLE', 'Hyundai Getz Prime',
        'Hyundai Grand i10', 'Hyundai Santro', 'Hyundai Santro AE',
        'Hyundai Santro Xing', 'Hyundai Sonata Transform', 'Hyundai Verna',
        'Hyundai Verna 1.4', 'Hyundai Verna 1.6', 'Hyundai Verna Fluidic',
        'Hyundai Verna Transform', 'Hyundai Verna VGT',
        'Hyundai Xcent Base', 'Hyundai Xcent SX', 'Hyundai i10',
        'Hyundai i10 Era', 'Hyundai i10 Magna', 'Hyundai i10 Sportz',
        'Hyundai i20', 'Hyundai i20 Active', 'Hyundai i20 Asta',
        'Hyundai i20 Magna', 'Hyundai i20 Select', 'Hyundai i20 Sportz',
        'Jaguar XE XE', 'Jaguar XF 2.2', 'Jeep Wrangler Unlimited',
        'Land Rover Freelander', 'Mahindra Bolero DI',
        'Mahindra Bolero Power', 'Mahindra Bolero SLE',
        'Mahindra Jeep CL550', 'Mahindra Jeep MM', 'Mahindra KUV100',
        'Mahindra KUV100 K8', 'Mahindra Logan', 'Mahindra Logan Diesel',
        'Mahindra Quanto C4', 'Mahindra Quanto C8', 'Mahindra Scorpio',
        'Mahindra Scorpio 2.6', 'Mahindra Scorpio LX',
        'Mahindra Scorpio S10', 'Mahindra Scorpio S4',
        'Mahindra Scorpio SLE', 'Mahindra Scorpio SLX',
        'Mahindra Scorpio VLX', 'Mahindra Scorpio Vlx',
        'Mahindra Scorpio W', 'Mahindra TUV300 T4', 'Mahindra TUV300 T8',
        'Mahindra Thar CRDe', 'Mahindra XUV500', 'Mahindra XUV500 W10',
        'Mahindra XUV500 W6', 'Mahindra XUV500 W8', 'Mahindra Xylo D2',
        'Mahindra Xylo E4', 'Mahindra Xylo E8', 'Maruti Suzuki 800',
        'Maruti Suzuki A', 'Maruti Suzuki Alto', 'Maruti Suzuki Baleno',
        'Maruti Suzuki Celerio', 'Maruti Suzuki Ciaz',
        'Maruti Suzuki Dzire', 'Maruti Suzuki Eeco',
        'Maruti Suzuki Ertiga', 'Maruti Suzuki Esteem',
        'Maruti Suzuki Estilo', 'Maruti Suzuki Maruti',
        'Maruti Suzuki Omni', 'Maruti Suzuki Ritz', 'Maruti Suzuki S',
        'Maruti Suzuki SX4', 'Maruti Suzuki Stingray',
        'Maruti Suzuki Swift', 'Maruti Suzuki Versa',
        'Maruti Suzuki Vitara', 'Maruti Suzuki Wagon', 'Maruti Suzuki Zen',
        'Mercedes Benz A', 'Mercedes Benz B', 'Mercedes Benz C',
        'Mercedes Benz GLA', 'Mini Cooper S', 'Mitsubishi Lancer 1.8',
        'Mitsubishi Pajero Sport', 'Nissan Micra XL', 'Nissan Micra XV',
        'Nissan Sunny', 'Nissan Sunny XL', 'Nissan Terrano XL',
        'Nissan X Trail', 'Renault Duster', 'Renault Duster 110',
        'Renault Duster 110PS', 'Renault Duster 85', 'Renault Duster 85PS',
        'Renault Duster RxL', 'Renault Kwid', 'Renault Kwid 1.0',
        'Renault Kwid RXT', 'Renault Lodgy 85', 'Renault Scala RxL',
        'Skoda Fabia', 'Skoda Fabia 1.2L', 'Skoda Fabia Classic',
        'Skoda Laura', 'Skoda Octavia Classic', 'Skoda Rapid Elegance',
        'Skoda Superb 1.8', 'Skoda Yeti Ambition', 'Tata Aria Pleasure',
        'Tata Bolt XM', 'Tata Indica', 'Tata Indica V2', 'Tata Indica eV2',
        'Tata Indigo CS', 'Tata Indigo LS', 'Tata Indigo LX',
        'Tata Indigo Marina', 'Tata Indigo eCS', 'Tata Manza',
        'Tata Manza Aqua', 'Tata Manza Aura', 'Tata Manza ELAN',
        'Tata Nano', 'Tata Nano Cx', 'Tata Nano GenX', 'Tata Nano LX',
        'Tata Nano Lx', 'Tata Sumo Gold', 'Tata Sumo Grande',
        'Tata Sumo Victa', 'Tata Tiago Revotorq', 'Tata Tiago Revotron',
        'Tata Tigor Revotron', 'Tata Venture EX', 'Tata Vista Quadrajet',
        'Tata Zest Quadrajet', 'Tata Zest XE', 'Tata Zest XM',
        'Toyota Corolla', 'Toyota Corolla Altis', 'Toyota Corolla H2',
        'Toyota Etios', 'Toyota Etios G', 'Toyota Etios GD',
        'Toyota Etios Liva', 'Toyota Fortuner', 'Toyota Fortuner 3.0',
        'Toyota Innova 2.0', 'Toyota Innova 2.5', 'Toyota Qualis',
        'Volkswagen Jetta Comfortline', 'Volkswagen Jetta Highline',
        'Volkswagen Passat Diesel', 'Volkswagen Polo',
        'Volkswagen Polo Comfortline', 'Volkswagen Polo Highline',
        'Volkswagen Polo Highline1.2L', 'Volkswagen Polo Trendline',
        'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
        'Volkswagen Vento Konekt', 'Volvo S80 Summum'], dtype=object),
 array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
        'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
        'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
        'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['Diesel', 'LPG', 'Petrol'], dtype=object)]

In [41]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),
                                    remainder='passthrough')

In [42]:
lr=LinearRegression()

In [43]:
pipe=make_pipeline(column_trans,lr)

In [44]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [45]:
y_pred=pipe.predict(X_test)

In [46]:
r2_score(y_test,y_pred)

0.7166473809692153

In [47]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    scores.append(r2_score(y_test,y_pred))

In [48]:
scores

[0.6396886265642636,
 0.5707720997332639,
 0.6120218901905264,
 0.47539857245225725,
 0.7936282883865851,
 0.6041745386762984,
 0.4448651196738874,
 0.5203869570117414,
 0.537650180840765,
 0.6454178162855656,
 0.6669268612446471,
 0.6569983212804802,
 0.46013883139698275,
 0.5970124350861385,
 0.6969604235776939,
 0.5988392388277025,
 0.4690923655445546,
 0.6829984248086884,
 0.5748962239640879,
 0.7054392884017386,
 0.7178766735068903,
 0.38730113170034197,
 0.6440007174412241,
 0.5752180403262248,
 0.45755937559323856,
 0.483973540766647,
 0.7341140963415183,
 0.7364714089054041,
 0.6978488421894156,
 0.5960515921527336,
 0.6767634419069708,
 0.8447014798608911,
 0.7441062910025096,
 0.758562814539653,
 0.6369433087947666,
 0.7978505321000228,
 0.505283851312688,
 0.48563528751324936,
 0.48789464543491357,
 0.7621633235966896,
 0.4251218394378139,
 0.6947692529320734,
 0.484904514119894,
 0.5153600054288507,
 0.6071069480133494,
 0.7119725099287986,
 0.47062032724077874,
 0.4720901864615715,
 0.7680566614566731,
 0.7720389033692592,
 0.49862747890630144,
 0.6154231413750617,
 0.7811817625715344,
 0.7611024901984292,
 0.5711382755353219,
 0.7423398108547596,
 0.859864780272317,
 0.7500325695411102,
 0.7151715833339083,
 0.25491379890382637,
 0.49115635470165575,
 0.5198267784568484,
 0.47493039775796486,
 0.6848770976727822,
 0.574164750139041,
 0.5269148121502614,
 0.5824168521673071,
 0.6317817897265509,
 0.728087846046209,
 0.7404591259923823,
 0.7512752059134719,
 0.7566840310458669,
 0.5964871723358709,
 0.7206703273762861,
 0.5306516583718537,
 0.632885797386395,
 0.5344067162575608,
 0.7348764330917317,
 0.47603959820736685,
 0.6920887403482087,
 0.42747569766793414,
 0.4404119466992711,
 0.6209692527957238,
 0.7886190947635385,
 0.7886980948286664,
 0.6591645015335272,
 0.7076027817888173,
 0.48680757913861095,
 0.627560224535789,
 0.5997303504771154,
 0.7102820688739724,
 0.5791127626897106,
 0.7198164662215946,
 0.5839273847101882,
 0.5915047223123964,
 0.6323556935227237,
 0.6510765308158657,
 0.7205914912828806,
 0.598645995384682,
 0.6144475258937252,
 0.7399321850679754,
 0.6449501571242031,
 0.7177567745800666,
 0.6456678287978255,
 0.6506412972575484,
 0.6440924645727915,
 0.47207622656357684,
 0.4688969453158536,
 0.5133513293164418,
 0.8154921563178139,
 0.8120482743863703,
 0.6669251440227579,
 0.49633206896455373,
 0.7415853973522728,
 0.5222265331374085,
 0.5743812784934008,
 0.6310626666899526,
 0.61226334434435,
 0.4967280456360188,
 0.743791729136337,
 0.7318113693762704,
 0.6520185242732315,
 0.7441843872727276,
 0.640404949577162,
 0.7268348571758685,
 0.6014190937078696,
 0.7518405126377944,
 0.8444220198199711,
 0.5272093271832559,
 0.5488750255047641,
 0.5914251298148296,
 0.5809775468450937,
 0.5884596993367495,
 0.6258056562815916,
 0.7143326438632394,
 0.8247983650235766,
 0.522644695325934,
 0.6738572366624143,
 0.5645936691747485,
 0.7226790520633244,
 0.5966805067417333,
 0.5593419707990679,
 0.7455123021327819,
 0.3430399107603148,
 0.7160889349765452,
 0.7140213912405406,
 0.7079205362994727,
 0.4982081889888753,
 0.510597838625467,
 0.5709854946714128,
 0.4501886231694864,
 0.8326239247599114,
 0.574021956503402,
 0.4822588640929265,
 0.6963197937674885,
 0.5901369847084749,
 0.3561256063180206,
 0.8150881205365564,
 0.5890888047283966,
 0.682500743444381,
 0.6151018815318913,
 0.4755131540452566,
 0.6583955999859427,
 0.4708671114128783,
 0.6054457143125409,
 0.6266494530479432,
 0.7470352835562217,
 0.6609560924437601,
 0.45814797058812295,
 0.721527773858115,
 0.8169403231780659,
 0.8082453642280506,
 0.8332492356979442,
 0.773918224059775,
 0.5843814273543115,
 0.18201797995480884,
 0.6857342396011776,
 0.59278153135738,
 0.6749825008712453,
 0.6422192853238945,
 0.638085378008751,
 0.6041773672086931,
 0.6238085196298773,
 0.611981912262932,
 0.606240850670964,
 0.6689091139517152,
 0.656598262936827,
 0.6638591061050065,
 0.6844042682566854,
 0.5581469536532663,
 0.7824578774907448,
 0.6774259321352055,
 0.7502626643335047,
 0.6787735375738477,
 0.715021103292901,
 0.4646290899476735,
 -0.10200113090916507,
 0.6875715492789561,
 0.467416073478351,
 0.6622284382415635,
 0.6515343714805106,
 0.46928130804047774,
 0.5601334061017598,
 0.7422610720114906,
 0.6031511707812294,
 0.6151471721322443,
 0.7235239618026668,
 0.5733686028123572,
 0.6797274139998308,
 0.5318334064846846,
 0.5108533762197112,
 0.5936085521454646,
 0.5958451206720178,
 0.604167921171413,
 0.6571551615019231,
 0.47883626432934456,
 0.583820892247361,
 0.5796188353170769,
 0.6500736782973064,
 0.6767849697422588,
 0.6325576195930882,
 0.6781052540013546,
 0.4949766555016142,
 0.44692350380526813,
 0.4600195361000027,
 0.7383050109591873,
 0.6768101145067373,
 0.6608586485268597,
 0.6425711672302753,
 0.4982414851352851,
 0.504752889056005,
 0.573053848416972,
 0.5521067859554227,
 0.5910573861583284,
 0.812842372150929,
 0.7698994789883157,
 0.8407340290766382,
 0.6918603855933896,
 0.43272764549030895,
 0.5719634107970304,
 0.7087384023328882,
 0.35293037538490724,
 0.6000136046703408,
 0.7556920173468565,
 0.5280532466895677,
 0.7527740772584816,
 0.7824619792310272,
 0.823417403443515,
 0.7653628662710716,
 0.27190688162356114,
 0.4644301870866775,
 0.3693289693882972,
 0.4317344193670346,
 0.6919439765494042,
 0.6822602934635439,
 0.7685969108246926,
 0.5503126318296736,
 0.5397841389039519,
 0.5523848276819993,
 0.40811388003133886,
 0.7765424974280755,
 0.6697151042799727,
 0.8072421641298643,
 0.7252231768067741,
 0.500907872589127,
 0.4050559036970811,
 0.6879805482420995,
 0.616396401377461,
 0.5430457240750064,
 0.42272730799312386,
 0.5725081702082222,
 0.6007071070012312,
 0.728146770792951,
 0.6400459209052843,
 0.6219075729500942,
 0.5329113142183268,
 0.6530403943659141,
 0.6008168310215979,
 0.7635188624139602,
 0.7587541621083737,
 0.5657650124132243,
 0.6950670493791673,
 0.6647912656382339,
 0.6628272549645685,
 0.7834295341070467,
 0.47810433620341075,
 0.7779347009846268,
 0.6187424911760651,
 0.4835831493784779,
 0.6116850756251333,
 0.5837969070998661,
 0.5972815205444644,
 0.7670045772356346,
 0.7382130368936866,
 0.8272796450166282,
 0.5009938465857517,
 0.7077575806436875,
 0.6984695979382602,
 0.6689521564232084,
 0.6785514865973348,
 0.7351885488425536,
 0.6625942227826802,
 0.8991190499074018,
 0.5562326911888228,
 0.7714731871765844,
 0.606326566274269,
 0.7417408331683291,
 0.6881722133605228,
 0.5274860798855758,
 0.7158216657040912,
 0.7632583011230083,
 0.6971531467056299,
 0.36921518210159965,
 0.4137458058525545,
 0.5203540878309991,
 0.7201024333872359,
 0.5522673480045621,
 0.48181061703553396,
 0.5607403718751421,
 0.6156448664919341,
 0.573416708061611,
 0.7677465450063857,
 0.4737080413621556,
 0.5740570032412047,
 0.5560428240733049,
 0.5712192127118962,
 0.6692160379662913,
 0.5682625329288575,
 0.6412010806580484,
 0.5629477429558294,
 0.6123827429619089,
 0.674354651824618,
 0.6323572364405057,
 0.5189877908516014,
 0.7123626792195961,
 0.5799857904797943,
 0.4853516191647441,
 0.6664054284593155,
 0.7559572985389289,
 0.5322532651310694,
 0.6735017948668813,
 0.7274389864632955,
 0.78324081355253,
 0.6398070754640216,
 0.6115152660392746,
 0.6881760548049468,
 0.6139108566505747,
 0.5418456063511434,
 0.48536659896418366,
 0.6441212969040636,
 0.6553640537600942,
 0.6452796390551518,
 0.8304416353682713,
 0.4283873016293763,
 0.6681390360728824,
 0.6907718907231404,
 0.6186353420278274,
 0.6803276971450856,
 0.6856150378246229,
 0.6318682372459932,
 0.6558976530903735,
 0.5425209280326636,
 0.4437177850827658,
 0.7099135718219202,
 0.7211569574521737,
 0.6575198063275814,
 0.766311874324227,
 0.42601467990677644,
 0.7273458558874927,
 0.7745482731511442,
 0.7111781494761028,
 0.46699660238015717,
 0.503749402053552,
 0.6521235136101372,
 0.370550388235117,
 0.5845640165222821,
 0.6626433797873168,
 0.5841512846920307,
 0.8034866556371328,
 0.750143326105813,
 0.49139304445376064,
 0.7760770802242233,
 0.6939757376439363,
 0.8445170883178518,
 0.6831041334391657,
 0.6696611080070987,
 0.7251697305507845,
 0.4762710120167759,
 0.5262184627931903,
 0.41912280982558614,
 0.7884853070439986,
 0.6611503513139168,
 0.8176413729656304,
 0.5382924336917604,
 0.5887471062339327,
 0.6875144601893883,
 0.5454195071853081,
 0.5892872572643995,
 0.4955086849254814,
 0.7126785613235065,
 0.5932649259141888,
 0.6500408304661933,
 0.7652948367574056,
 0.43832974715331674,
 0.742910447364307,
 0.18536176681696304,
 0.5408359119313508,
 0.7031886521202801,
 0.6720671738320682,
 0.6359342323970325,
 0.7046639242772477,
 0.6658965105476831,
 0.6532611210363366,
 0.6813573777342836,
 0.7289721573848318,
 0.605959655567242,
 0.6375611338896627,
 0.7504186236104565,
 0.6507191404686676,
 0.6167577441452544,
 0.7137538958334158,
 0.6776104704033818,
 0.6372952222891233,
 0.45585529806737135,
 0.6659614535164352,
 0.5585104654863876,
 0.4272670748583548,
 0.7705404640956631,
 0.5378234811333088,
 0.7790635155638366,
 0.6322581395707183,
 0.8231944901979799,
 0.7353551112719506,
 0.7879486215426309,
 0.48809011815042425,
 0.7608098606262831,
 0.5329740394225166,
 0.5717755610990038,
 0.5495499278602127,
 0.7428223000089986,
 0.6652076416729058,
 0.6455871076440693,
 0.7980732523126635,
 0.7613142836570137,
 0.7939718851016515,
 0.6415268588948319,
 0.737941191561441,
 0.6433892992021523,
 0.6325656466863956,
 0.7002105377005348,
 0.6277384959166119,
 0.537134563279,
 0.7431773030191072,
 0.5961797964583241,
 0.5749484959881674,
 0.6719869783695092,
 0.3540671160421526,
 0.40830878920907276,
 0.6671175271403302,
 0.6706876697166938,
 0.735963637532413,
 0.48764507602369134,
 0.6679233600443986,
 0.8588440340852193,
 0.4112130162204699,
 0.6489515210388687,
 0.4707132433008032,
 0.6513549415808226,
 0.6641669524286091,
 0.5761344761142096,
 0.6259886361569099,
 0.43546970820129616,
 0.25227942114421187,
 0.6482769545038606,
 0.7042844434150796,
 0.710846476657012,
 0.5531440515746548,
 0.6762504488296213,
 0.7342347165995067,
 0.5423693528782032,
 0.6890434895696536,
 0.5966340482352407,
 0.8096476520917656,
 0.7433541284630447,
 0.6996280606930421,
 0.6548057235724736,
 0.5704510102289588,
 0.5390066716624038,
 0.7672813241057238,
 0.5955546240869951,
 0.4590981397843801,
 0.7727271949172159,
 0.6543702501183657,
 0.5153310084961086,
 0.6094213455042873,
 0.5281927807249196,
 0.6618966000431854,
 0.5898841083368722,
 0.6686099098963845,
 0.8451122140167118,
 0.685154785837048,
 0.5853706492383809,
 0.6740271319825819,
 0.6871818575167372,
 0.6606741774563543,
 0.6003120435314915,
 0.531166998250073,
 0.8592900413648072,
 0.611407419972016,
 0.6491170504358195,
 0.6810764741841199,
 0.8456102255987847,
 0.6631974619808068,
 0.7452277765497851,
 0.6402073272347666,
 0.8244654805414865,
 0.7360765711960089,
 0.7350753360105229,
 0.5941848976696712,
 0.6962318297374832,
 0.7593752759333025,
 0.6418316528497807,
 0.67186877655576,
 0.5621312965573452,
 0.7266191773669035,
 0.38455954791934566,
 0.6375946086655466,
 0.6313349763911502,
 0.8035149887973367,
 0.6221482330490449,
 0.6169265546999533,
 0.4992642802067362,
 0.46485690380260836,
 0.727832805696403,
 0.6693022365230827,
 0.7235212464333608,
 0.5299339367166087,
 0.6988745073203115,
 0.6929331825840082,
 0.615708868604611,
 0.6845409026243399,
 0.5161384921473039,
 0.7035439324337932,
 0.7382341949833797,
 0.6517066825854971,
 0.4622193172192327,
 0.7246923879311128,
 0.41541947545154456,
 0.6372959348005262,
 0.4128287096482929,
 0.5571583239653037,
 0.8106485251625116,
 0.6476888732175146,
 0.7924900690342822,
 0.604045673954331,
 0.6913356728337486,
 0.4389209624658428,
 0.5432390981065632,
 0.6555498388886595,
 0.6192012600470844,
 0.5830022470472745,
 0.49861829311214845,
 0.7210397716994321,
 0.35795321812517333,
 0.595205988322033,
 0.6809422585729958,
 0.7707641862156851,
 0.6126161917125668,
 0.7873569820803704,
 0.5246278883204705,
 0.5946042554627933,
 0.7126615638774516,
 0.6090479098039843,
 0.6302773757029032,
 0.7506417728121147,
 0.7485120618669296,
 0.7364836273410621,
 0.6558251540612892,
 0.4645395641655016,
 0.5480374168289037,
 0.5372799474278813,
 0.744313901793165,
 0.4389751824699707,
 0.7933327459544108,
 0.4176743624797098,
 0.5095238436502253,
 0.83176140582585,
 0.7535636204853475,
 0.7631363336415742,
 0.7310521461752983,
 0.787163217123843,
 0.6346252642029494,
 0.8131465215831252,
 0.7987222388695181,
 0.6619858573968527,
 0.27598572182832626,
 0.5137432885072166,
 0.3998702053030321,
 0.740604646837155,
 0.4500838420455304,
 0.48529604136129934,
 0.7244466185886191,
 0.7208685262985575,
 0.6634913825600706,
 0.4391403757334208,
 0.7913742498582925,
 0.4744385223270374,
 0.6984679806692864,
 0.7445466111426531,
 0.6459606815832838,
 0.4235810384646884,
 0.40245861262926375,
 0.5836431677548697,
 0.6049824489286021,
 0.7188286323981548,
 0.7233176085268124,
 0.430731521291974,
 0.6322023878298372,
 0.6136308104028468,
 0.5271638452520168,
 0.504450758295712,
 0.6586570643826258,
 0.5479014978022565,
 0.6903555353507385,
 0.8164082706619018,
 0.46243679918726954,
 0.43993838410780906,
 0.48372100459952294,
 0.6437727330950749,
 0.5817202186241406,
 0.5884610233969139,
 0.5985054134551642,
 0.7053576053023016,
 0.6584079079208025,
 0.2915039977486519,
 0.6924574909029789,
 0.8735910356317127,
 0.6753412508687437,
 0.7605849044787777,
 0.7172468739090092,
 0.5792507021122927,
 0.6010156291230686,
 0.6040313264082611,
 0.5933039892183929,
 0.40501310630790854,
 0.6984732196774786,
 0.6694888474269418,
 0.607995963978275,
 0.7535567512870276,
 0.8175850970900816,
 0.6590218423658096,
 0.4511635151635459,
 0.7349319266587937,
 0.7307488771572688,
 0.531898278970744,
 0.8666936803147118,
 0.6513314447913598,
 0.44393003861839975,
 0.6659447400959422,
 0.7001650670381191,
 0.5239233364783524,
 0.7234572011151562,
 0.5241399957536027,
 0.5386840228703869,
 0.5289564541158218,
 0.5170086919107126,
 0.6502420960910912,
 0.7254306636532803,
 0.724907747973139,
 0.7346326805888799,
 0.7477749664702216,
 0.5886695169700372,
 0.611558572801793,
 0.6783808478794455,
 0.5845568824170906,
 0.6613290757824575,
 0.608672029090628,
 0.4903609230169288,
 0.7998096839302649,
 0.6527534162205613,
 0.7232341272647629,
 0.5484187749408338,
 0.7447065165640634,
 0.6589267362232096,
 0.5685275203710002,
 0.6144913555153921,
 0.8262228444325719,
 0.6391657314520747,
 0.5597182445453308,
 0.7557008577239042,
 0.6589084189002359,
 0.7031961008674021,
 0.6866694788146923,
 0.6618051289038389,
 0.7313098374444881,
 0.7085975425954265,
 0.7221241123034434,
 0.6128989946972219,
 0.747852481067676,
 0.6888902621776449,
 0.4735873855384263,
 0.7107128888119645,
 0.5648394596302855,
 0.7628233808401865,
 0.5356813984503861,
 0.6270522244348444,
 0.6284158317834496,
 0.5599732485822287,
 0.5512132976749775,
 0.33839463312970297,
 0.5873195088127324,
 0.758848273685149,
 0.7977590919931322,
 0.7688371688112305,
 0.4529685808559363,
 0.7102083973029805,
 0.7795020754744015,
 0.5598444122455826,
 0.4358209494990909,
 0.6618271003537406,
 0.47923779493520813,
 0.6050520556201687,
 0.7074626621170582,
 0.807361457047841,
 0.6526296127716686,
 0.4876850239313423,
 0.6357134035977714,
 0.6574946890480001,
 0.5372351694221558,
 0.7597314034501454,
 0.6249827598700256,
 0.7191329493980516,
 0.7964141010666042,
 0.6018177743056837,
 0.537896124186869,
 0.4412515551314512,
 0.7025808255366355,
 0.5420619892523107,
 0.5494151221385619,
 0.5686222876547524,
 0.6936367644580883,
 0.6087451684569974,
 0.677572217346487,
 0.7333314623799219,
 0.5724430933988531,
 0.6378010075744752,
 0.74648255993979,
 0.5220152144675169,
 0.4809235505403452,
 0.4152441338417543,
 0.5603032818518485,
 0.7072446661175968,
 0.6816550072925349,
 0.7152707356963133,
 0.6634022029808022,
 0.5810826791781679,
 0.4588703252793289,
 0.7086980404740857,
 0.5657498877641273,
 0.5189835628771815,
 0.6652799904700948,
 0.720699472014432,
 0.7178906597704756,
 0.5736883169917422,
 0.6935881010486781,
 0.5744700223346988,
 0.6279413689149335,
 0.5983041725113882,
 0.40934854471032456,
 0.7680829891650854,
 0.514455633913575,
 0.638133492305249,
 0.7619603486212608,
 0.6401958484976563,
 0.498282753872091,
 0.5288234150248456,
 0.6034401464111152,
 0.4883787902695389,
 0.7353058227881937,
 0.5820207196611678,
 0.7421802218689053,
 0.7765335360179146,
 0.7148905891257975,
 0.8183206967194683,
 0.6846445496458254,
 0.49833245437020535,
 0.644325613086908,
 0.5691589025735313,
 0.5077680458533746,
 0.41519588790130024,
 0.8004808851635767,
 0.7256359877048979,
 0.7605270875173593,
 0.741063217593284,
 0.6527388706880357,
 0.7241984211550786,
 0.7602799439890653,
 0.47542155920362505,
 0.39251226544759543,
 0.6574127271396795,
 0.6202460003335786,
 0.44287862951454615,
 0.6884979757634102,
 0.6549462052714788,
 0.7954625355809745,
 0.6893897233488204,
 0.6593148058245816,
 0.8262121014229666,
 0.43248848968058595,
 0.6937689403422735,
 0.4558582199036708,
 0.6056541672657935,
 0.6697952185321749,
 0.5851937108827587,
 0.8306564979467131,
 0.4465228360776602,
 0.6331445740790528,
 0.8372996154642242,
 0.7201034549180223,
 0.5550890490443845,
 0.6876665858052073,
 0.6382268447022341,
 0.6860732115413051,
 0.7208576356475315,
 0.43701919269347,
 0.67609063360519,
 0.6263675742442545,
 0.5737979891548989,
 0.4858339325844635,
 0.6286011222599368,
 0.4485737905167919,
 0.6541291496646506,
 0.8142886389131644,
 0.5427077346790463,
 0.7103802593334787,
 0.6091901757316498,
 0.6787400012018192,
 0.6060319061241008,
 0.4944463125926085,
 0.6728370891435589,
 0.723113100548137,
 0.8456557545425636,
 0.7274032871922188,
 0.7248784839397042,
 0.6451585070260161,
 0.7486401273340468,
 0.6358791390989775,
 0.6268057447318409,
 0.7651523488428998,
 0.7103300894574491,
 0.7320464622758036,
 0.744311864863446,
 0.6488461777028904,
 0.7020151050676346,
 0.7266890625655467,
 0.6348974948867961,
 0.44909864810376565,
 0.43251279357951433,
 0.7679404927515351,
 0.5133168516583682,
 0.6810119366830856,
 0.6756894488380922,
 0.5620271449262295,
 0.6848138955241008,
 0.618402839109375,
 0.28212704945592404,
 0.6083036667875732,
 0.5629829468648968,
 0.6051302081891435,
 0.6578224558085923,
 0.5899535002681502,
 0.6602440062701985,
 0.7279158890726487,
 0.64232047594498,
 0.8263248508678127,
 0.7256963928094623,
 0.6762402074898289,
 0.5329785740678971,
 0.6941707560717039,
 0.6558855117502058,
 0.7333521168185752,
 0.6259269647617993,
 0.5573394859359085,
 0.7388865791897272,
 0.7673189948886665,
 0.6035344568634629,
 0.42198832916148843,
 0.7593924041101843,
 0.7933422035101136,
 0.576497216759196,
 0.7884235798205304,
 0.5416205826872247,
 0.6434410414111759,
 0.5579136553415529,
 0.5369146183837208,
 0.6583555751793054,
 0.42164646263967687,
 0.6530141778023533,
 0.7496585668658442,
 0.5856128772095376,
 0.8020853934600305,
 0.6774233130106011,
 0.40931580748228835,
 0.8095607047101231,
 0.6636790723420203,
 0.6586191108641856,
 0.7770065000755321,
 0.6583616568400644,
 0.718099537450504,
 0.7534210040469915,
 0.7654048110060134,
 0.5572413494734418,
 0.61083667478263,
 0.5180415016211917,
 0.5989798372448158,
 0.7106939707385564,
 0.447352769662843,
 0.47431751367746067,
 0.7462254448625723,
 0.414244706517912,
 0.5874231006973544,
 0.7496885803625186,
 0.7823486975650413,
 0.7553344911511783,
 0.684630854443699,
 0.7672674660167736,
 0.793735337873652,
 0.5940140599996311,
 0.5381676080272098,
 0.6075619439632722,
 0.4114479326227388,
 0.7613220914428396,
 0.5336975323214594,
 0.7140861005119409,
 0.6656436903097451,
 0.5920405535481719,
 0.7055166521863723,
 0.6782170329393675,
 0.7721979754180524,
 0.5800689142436106,
 0.6988411822790865,
 0.5885977058514973,
 0.7250602873392682,
 0.711570852711481,
 0.8262021229234104,
 0.7133956348787568,
 0.3791626828028928,
 0.6733495486255981,
 0.5949030678361158,
 0.7501697317080791,
 0.6145198187679194,
 0.5426793752701782,
 0.762995088160145,
 0.6479768790312339,

In [49]:
np.argmax(scores)

302

In [50]:
scores[np.argmax(scores)]

0.8991190499074018

In [51]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
r2_score(y_test,y_pred)

0.8991190499074018

In [52]:
import pickle

In [53]:
pickle.dump(pipe,open('LinearRegression.pkl','wb'))

In [66]:
pipe.predict(pd.DataFrame([['Ford EcoSport Titanium','Ford',2014,36000,'Diesel']],columns=['name','company','year','kms_driven','fuel_type']))

array([485639.02051655])

In [62]:
pipe.steps[0][1].transformers[0][1].categories[0]

array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat Diesel',
       'Chevrolet Beat LS', 'Chevrolet Beat LT', 'Chevrolet Beat PS',
       'Chevrolet Cruze LTZ', 'Chevrolet Enjoy', 'Chevrolet Enjoy 1.4',
       'Chevrolet Sail 1.2', 'Chevrolet Sail UVA', 'Chevrolet Spark',
       'Chevrolet Spark 1.0', 'Chevrolet Spark LS', 'Chevrolet Spark LT',
       'Chevrolet Tavera LS', 'Chevrolet Tavera Neo', 'Datsun GO T',
       'Datsun Go Plus', 'Datsun Redi GO', 'Fiat Linea Emotion',
       'Fiat Petra ELX', 'Fiat Punto Emotion', 'Force Motors Force',
       'Force Motors One', 'Ford EcoSport', 'Ford EcoSport Ambiente',
       'Ford EcoSport Titanium', 'Ford EcoSport Trend',
       'Ford Endeavor 4x4', 'Ford Fiesta', 'Ford Fiesta SXi', 'Ford Figo',
       'Ford Figo Diesel', 'Ford Figo Duratorq', 'Ford Figo Petrol',
       'Ford Fusion 1.4', 'Ford Ikon 1.3', 'Ford Ikon 1.6',
       'Hindustan Motors Ambassador', 'Honda Accord', 'Honda Amaze',
       'Honda Amaze 1.2', 'Honda Amaze 1.5', 'Honda Brio', 'Honda Brio V',
       'Honda Brio VX', 'Honda City', 'Honda City 1.5', 'Honda City SV',
       'Honda City VX', 'Honda City ZX', 'Honda Jazz S', 'Honda Jazz VX',
       'Honda Mobilio', 'Honda Mobilio S', 'Honda WR V', 'Hyundai Accent',
       'Hyundai Accent Executive', 'Hyundai Accent GLE',
       'Hyundai Accent GLX', 'Hyundai Creta', 'Hyundai Creta 1.6',
       'Hyundai Elantra 1.8', 'Hyundai Elantra SX', 'Hyundai Elite i20',
       'Hyundai Eon', 'Hyundai Eon D', 'Hyundai Eon Era',
       'Hyundai Eon Magna', 'Hyundai Eon Sportz', 'Hyundai Fluidic Verna',
       'Hyundai Getz', 'Hyundai Getz GLE', 'Hyundai Getz Prime',
       'Hyundai Grand i10', 'Hyundai Santro', 'Hyundai Santro AE',
       'Hyundai Santro Xing', 'Hyundai Sonata Transform', 'Hyundai Verna',
       'Hyundai Verna 1.4', 'Hyundai Verna 1.6', 'Hyundai Verna Fluidic',
       'Hyundai Verna Transform', 'Hyundai Verna VGT',
       'Hyundai Xcent Base', 'Hyundai Xcent SX', 'Hyundai i10',
       'Hyundai i10 Era', 'Hyundai i10 Magna', 'Hyundai i10 Sportz',
       'Hyundai i20', 'Hyundai i20 Active', 'Hyundai i20 Asta',
       'Hyundai i20 Magna', 'Hyundai i20 Select', 'Hyundai i20 Sportz',
       'Jaguar XE XE', 'Jaguar XF 2.2', 'Jeep Wrangler Unlimited',
       'Land Rover Freelander', 'Mahindra Bolero DI',
       'Mahindra Bolero Power', 'Mahindra Bolero SLE',
       'Mahindra Jeep CL550', 'Mahindra Jeep MM', 'Mahindra KUV100',
       'Mahindra KUV100 K8', 'Mahindra Logan', 'Mahindra Logan Diesel',
       'Mahindra Quanto C4', 'Mahindra Quanto C8', 'Mahindra Scorpio',
       'Mahindra Scorpio 2.6', 'Mahindra Scorpio LX',
       'Mahindra Scorpio S10', 'Mahindra Scorpio S4',
       'Mahindra Scorpio SLE', 'Mahindra Scorpio SLX',
       'Mahindra Scorpio VLX', 'Mahindra Scorpio Vlx',
       'Mahindra Scorpio W', 'Mahindra TUV300 T4', 'Mahindra TUV300 T8',
       'Mahindra Thar CRDe', 'Mahindra XUV500', 'Mahindra XUV500 W10',
       'Mahindra XUV500 W6', 'Mahindra XUV500 W8', 'Mahindra Xylo D2',
       'Mahindra Xylo E4', 'Mahindra Xylo E8', 'Maruti Suzuki 800',
       'Maruti Suzuki A', 'Maruti Suzuki Alto', 'Maruti Suzuki Baleno',
       'Maruti Suzuki Celerio', 'Maruti Suzuki Ciaz',
       'Maruti Suzuki Dzire', 'Maruti Suzuki Eeco',
       'Maruti Suzuki Ertiga', 'Maruti Suzuki Esteem',
       'Maruti Suzuki Estilo', 'Maruti Suzuki Maruti',
       'Maruti Suzuki Omni', 'Maruti Suzuki Ritz', 'Maruti Suzuki S',
       'Maruti Suzuki SX4', 'Maruti Suzuki Stingray',
       'Maruti Suzuki Swift', 'Maruti Suzuki Versa',
       'Maruti Suzuki Vitara', 'Maruti Suzuki Wagon', 'Maruti Suzuki Zen',
       'Mercedes Benz A', 'Mercedes Benz B', 'Mercedes Benz C',
       'Mercedes Benz GLA', 'Mini Cooper S', 'Mitsubishi Lancer 1.8',
       'Mitsubishi Pajero Sport', 'Nissan Micra XL', 'Nissan Micra XV',
       'Nissan Sunny', 'Nissan Sunny XL', 'Nissan Terrano XL',
       'Nissan X Trail', 'Renault Duster', 'Renault Duster 110',
       'Renault Duster 110PS', 'Renault Duster 85', 'Renault Duster 85PS',
       'Renault Duster RxL', 'Renault Kwid', 'Renault Kwid 1.0',
       'Renault Kwid RXT', 'Renault Lodgy 85', 'Renault Scala RxL',
       'Skoda Fabia', 'Skoda Fabia 1.2L', 'Skoda Fabia Classic',
       'Skoda Laura', 'Skoda Octavia Classic', 'Skoda Rapid Elegance',
       'Skoda Superb 1.8', 'Skoda Yeti Ambition', 'Tata Aria Pleasure',
       'Tata Bolt XM', 'Tata Indica', 'Tata Indica V2', 'Tata Indica eV2',
       'Tata Indigo CS', 'Tata Indigo LS', 'Tata Indigo LX',
       'Tata Indigo Marina', 'Tata Indigo eCS', 'Tata Manza',
       'Tata Manza Aqua', 'Tata Manza Aura', 'Tata Manza ELAN',
       'Tata Nano', 'Tata Nano Cx', 'Tata Nano GenX', 'Tata Nano LX',
       'Tata Nano Lx', 'Tata Sumo Gold', 'Tata Sumo Grande',
       'Tata Sumo Victa', 'Tata Tiago Revotorq', 'Tata Tiago Revotron',
       'Tata Tigor Revotron', 'Tata Venture EX', 'Tata Vista Quadrajet',
       'Tata Zest Quadrajet', 'Tata Zest XE', 'Tata Zest XM',
       'Toyota Corolla', 'Toyota Corolla Altis', 'Toyota Corolla H2',
       'Toyota Etios', 'Toyota Etios G', 'Toyota Etios GD',
       'Toyota Etios Liva', 'Toyota Fortuner', 'Toyota Fortuner 3.0',
       'Toyota Innova 2.0', 'Toyota Innova 2.5', 'Toyota Qualis',
       'Volkswagen Jetta Comfortline', 'Volkswagen Jetta Highline',
       'Volkswagen Passat Diesel', 'Volkswagen Polo',
       'Volkswagen Polo Comfortline', 'Volkswagen Polo Highline',
       'Volkswagen Polo Highline1.2L', 'Volkswagen Polo Trendline',
       'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
       'Volkswagen Vento Konekt', 'Volvo S80 Summum'], dtype=object)